# basic options
title: New Awesome Blog 2020
author: Nick Morrow
email: nmorrow1111@yahoo.com
description: This website serves to provide a small view into my life and the road i've been on through college and where I wish it to take me.
twitter_username: nmorrow215
github_username: nmorrow-1111

# Build Settings
markdown: kramdown
theme: minima
