# basic options
title: Social Presence Blog 2020
author: Nick Morrow
email: nmorrow1111@yahoo.com
description: Small look into the life of Nick Morrow
twitter_username: nmorrow215
github_username: nmorrow-1111
linkedin_username: "Nicholas Morrow"
# Build Settings
markdown: kramdown
theme: minima
